services:
  web:
    build: .
    container_name: jobmatch_web
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - vector_store_data:/app/vector_store
      - job_data:/app/data
    depends_on:
      - worker

  worker:
    build: .
    container_name: jobmatch_worker
    restart: always
    entrypoint: ["python", "-m", "src.worker"]
    env_file:
      - .env
    volumes:
      - vector_store_data:/app/vector_store
      - job_data:/app/data

volumes:
  vector_store_data:
  job_data: